- hosts: master
  become: yes
  tasks:


    - name: apply
      become: no
      shell: >
        kubectl apply -f /home/vagrant/kubernetes/configMap.yaml && kubectl apply -f /home/vagrant/kubernetes/secrets.yaml && kubectl apply -f /home/vagrant/kubernetes/maria.yaml && kubectl apply -f /home/vagrant/kubernetes/flaskr.yaml

    - name: Install Calico network plugin
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

