# -*- mode: ruby -*-
# vi: set ft=ruby :

$provisionScript = <<-SCRIPT
sed -i 's#PasswordAuthentication no#PasswordAuthentication yes#g' /etc/ssh/sshd_config
systemctl restart sshd
SCRIPT

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false

  config.vm.provision "shell", inline: $provisionScript

  config.vm.define "UbuntuNice" do |ubuntu1|
    ubuntu1.vm.box = "ubuntu/jammy64"
    ubuntu1.vm.network "private_network", ip: "192.168.33.11"
    ubuntu1.vm.hostname = "UbuntuNice"
    ubuntu1.vm.provider "virtualbox" do |vb|
      vb.memory = "4096" # 4GB of RAM
      vb.cpus = 2        # 2 CPU cores
    end
  end
end
